### ISSUE TITLE
homebridge crashes when trying to access the DoorBird camera

### ISSUE THREAD

**Issue by axelbrunger** [hjdhjd/homebridge-doorbird#490]
With the most recent version of homebridge, the homebridge system crashes with trying to access the DoorBird camera:

TypeError: details.family.toLowerCase is not a function
    at /usr/local/lib/node_modules/homebridge-doorbird/node_modules/ip/lib/ip.js:385:39
    at Array.filter (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-doorbird/node_modules/ip/lib/ip.js:384:37
    at Array.map (<anonymous>)
    at Object.ip.address (/usr/local/lib/node_modules/homebridge-doorbird/node_modules/ip/lib/ip.js:379:37)
    at DoorbirdStreamingDelegate.prepareStream (/usr/local/lib/node_modules/homebridge-doorbird/src/doorbird-stream.ts:177:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Any suggestions?

**Comment by axelbrunger** [comment]
Has anybody else seen this behavior? Thank you.

**Comment by axelbrunger** [comment]
i just fixed the issue by installing the latest version of IP:

npm install ip

Please fix the dependency version number in the package.json for the homebridge-doorbird plugin or put a note in the instructions. 

Thank you.

**Comment by hjdhjd** [comment]
Thanks…I’ll try to push an update in the near future as well.
