### ISSUE TITLE
Disable Relay

### ISSUE THREAD

**Issue by jbk1988** [hjdhjd/homebridge-doorbird#67]
Hi,

Is there a way to disable a relay?

Thanks!

**Comment by hjdhjd** [comment]
Nope. You can rename it if you don't use it. I assume you mean disabling the non-primary relay, correct?

I might add support for disabling non-primary relays in a future release, but I'm trying to understand the use case. Can you elaborate on your reasoning?

**Comment by jbk1988** [comment]
I have a driveway gate and a sidewalk door that can both be unlocked, but because one has a HomeKit bridge, it's a duplicate. So, I'd like to get rid of the doorbird integration on one device for simplicity :)

**Comment by hjdhjd** [comment]
Stay tuned...have something in mind here in the next day or two.

**Comment by hjdhjd** [comment]
@jbk1988 I've just checked in v0.3.1 - give it a try. See the README for how to selectively hide relays.

**Comment by brownad** [comment]
Published

**Comment by jbk1988** [comment]
Thank you!

However, now that it has updated -- it all quit working for me. This is what I'm getting @brownad @hjdhjd:

```
error in configuring this Doorbird: StatusCodeError: 401 - "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n         \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>401 Unauthorized</title>\n </head>\n <body>\n  <h1>401 Unauthorized</h1>\n </body>\n</html>\n"
    at new StatusCodeError (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/hoobs/.hoobs/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  statusCode: 401,
  error: '<?xml version="1.0" encoding="iso-8859-1"?>\n' +
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n' +
    '         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n' +
    '<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n' +
    ' <head>\n' +
    '  <title>401 Unauthorized</title>\n' +
    ' </head>\n' +
    ' <body>\n' +
    '  <h1>401 Unauthorized</h1>\n' +
    ' </body>\n' +
    '</html>\n',
  options: [Object],
  response: [IncomingMessage]
}
```

**Comment by jbk1988** [comment]
Okay, I got that working by updating the password.

However, I no longer get notified when the doorbell is ringing in HomeKit. Is that a change now in the coding, @brownad? I deleted the HTTP call per the directions.
