### ISSUE TITLE
New version pushed...

### ISSUE THREAD

**Issue by hjdhjd** [hjdhjd/homebridge-doorbird#76]
@brownad - I pushed a big update through. I refactored the plugin, once more. :smile:

It now supports all the modern Homebridge APIs, rewritten in TypeScript for better maintainability.

Highlights...

- Audio support is automatically inferred. The plugin will validate whether the version of ffmpeg supports audio or not and act accordingly.
- Night vision configuration settings to enable night vision in various scenarios of interest, either full-time or only at night. We infer day / night through the user's timezone.
- Streamlined video and image configuration. This lays most of the foundation for two-way audio. I can't get the Doorbird API to accept a stream...once I do, I can move forward with it.
- As a result of the above, image snapshots are now generated much more quickly, without the need for ffmpeg.
- Simplified / removed some options that were no longer needed, and of course added new ones.
- Updated the documentation...and created a new logo for the project, hope you like it.

Test it out and let me know your thoughts. I've been running this for a week or so without issues.

To install it...in case you don't know / aren't familiar with typescript...

clone the repo.
Hop into the repo directory and run:

`npm run prepublishOnly`

That'll install it locally. If you do `npm -g install` in that local directory, it'll symlink into the system's node_modules and you can just reboot homebridge to test it out.

My suggestion is that you push this out as v1.0.0...but entirely your call, of course.

**Comment by brownad** [comment]
👀 thanks @hjdhjd

**Comment by brownad** [comment]
This is fantastic, can't believe the customisations you added.  If DoorBird ever implement HomeKit natively, sure they'll be watching this UX 👍 

You're right, a v1.0.0 is a better idea for version now that its Major again

**Comment by hjdhjd** [comment]
Thanks! Let me know if you have any questions or issues.

**Comment by hjdhjd** [comment]
I was working on a similar project and forked a version of my own code to create this...figured it’d be a nice contribution back, and would update this plugin so it’s staged for two-way audio. I’m still reverse-engineering uploading any audio to the Doorbird via the API. Have you had any success with audio-transmit in the API?

**Comment by brownad** [comment]
Going to test it out today.  It's a really amazing contribution, sets this up wonderfully.  I'd only got as far as trying out the example with gstreamer as per the LAN API docs.  what is failing to accept, is there a response from DB?

**Comment by brownad** [comment]
Possible problem.

[8/14/2020, 15:05:48] ERROR LOADING PLUGIN homebridge-doorbird:
[8/14/2020, 15:05:48] Error: Cannot find module 'C:\dev\npm\node_modules\homebridge-doorbird\dist\index.js'
Require stack:
- C:\dev\npm\node_modules\homebridge\lib\plugin.js
- C:\dev\npm\node_modules\homebridge\lib\pluginManager.js
- C:\dev\npm\node_modules\homebridge\lib\api.js
- C:\dev\npm\node_modules\homebridge\lib\server.js
- C:\dev\npm\node_modules\homebridge\lib\cli.js
- C:\dev\npm\node_modules\homebridge\bin\homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Plugin.load (C:\dev\npm\node_modules\homebridge\src\plugin.ts:181:27)
    at C:\dev\npm\node_modules\homebridge\src\pluginManager.ts:120:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (C:\dev\npm\node_modules\homebridge\src\pluginManager.ts:118:18)
    at Server.start (C:\dev\npm\node_modules\homebridge\src\server.ts:150:24)
    at cli (C:\dev\npm\node_modules\homebridge\src\cli.ts:80:10)
[8/14/2020, 15:05:48] ====================
[8/14/2020, 15:05:51] Error loading platform requested in your config.json at position 9
[8/14/2020, 15:05:51] Error: The requested platform 'Doorbird' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (C:\dev\npm\node_modules\homebridge\src\pluginManager.ts:224:15)
    at C:\dev\npm\node_modules\homebridge\src\server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (C:\dev\npm\node_modules\homebridge\src\server.ts:374:27)
    at Server.start (C:\dev\npm\node_modules\homebridge\src\server.ts:153:29)
    at cli (C:\dev\npm\node_modules\homebridge\src\cli.ts:80:10)
    at Object.<anonymous> (C:\dev\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

**Comment by brownad** [comment]
published BTW.

**Comment by hjdhjd** [comment]
When you publish the plugin, npm effectively runs a "make clean" in your working directory.

If you just do `npm run prepublishOnly` in your working directory it'll re-transpile the plugin.

**Comment by hjdhjd** [comment]
@brownad So the gstreamer example...did you get that working?

**Comment by brownad** [comment]
I did manage to publish correctly is something missing from the NPM package?

installing it I took it from NPM, am I the only one seeing this from the install? Sorry need some help on this :(

**Comment by brownad** [comment]
Didn’t spend enough time on it, wasn’t sure how it would work within ffmpeg also.  Seems plausible their example is showing it to work.  Guessing other platforms are using simple approaches with Doorbird too e.g. TinyCam

**Comment by brownad** [comment]
Ok sorted now, needed to close down homebridge completely

**Comment by brownad** [comment]
Installed and running, not receiving audio though.  Surfaced a problem I had calling JPEG image, was always super choppy, I used to take a restream from another source (ispy) was much faster.  I’ve updated the local config to respect the latest changes, but yes it is a lot simpler, there were too  many config items before… maybe too many	

I’ll keep testing it

**Comment by brownad** [comment]
Seems fine now.. audio and stream. Snapshots still choppy. But that might be down to hitting it over wifi, it has always been poor.. ispy via stillImage source was far smoother - grabs a small image 320 size. Was enough for a doorbell event

**Comment by brownad** [comment]
Think we can close this, works a charm

**Comment by hjdhjd** [comment]
Glad to hear it.
